Repository jrg4017/stock-simulator, pull requests merged in 2019-11, with the labels that each got.

#17 Asset abstraction and stock controller
  src/api/MarketService.py
  src/controllers/StockController.py
  src/models/assets/Asset.py
  src/models/assets/Stock.py
  src/models/collections/AssetMap.py
  src/models/collections/OwnedAssets.py
  src/models/collections/SoldAssets.py
  src/models/collections/Watchlist.py
Labels: back end

#19 Refactored for MySQL dependency
  src/api/requirements.txt
  src/controllers/StockController.py
  src/controllers/UserController.py
Labels: back end

#15 basic html pages, css setup
  src/_config.py
  src/api/main.py
  src/main.py
  src/views/static/styles/container-macro.css
  src/views/static/styles/footer.css
  src/views/static/styles/form.css
  src/views/static/styles/header.css
  src/views/static/styles/login.css
  src/views/static/styles/main.css
  src/views/static/styles/reset.css
  src/views/templates/account.html.j2
  src/views/templates/header-footer/footer.html.j2
  src/views/templates/header-footer/header.html.j2
  src/views/templates/index.html.j2
  src/views/templates/layout.html.j2
  src/views/templates/login/login.html.j2
  src/views/templates/login/password-reset.html.j2
  src/views/templates/login/register.html.j2
  src/views/templates/macros/container-macro.html.j2
  src/views/templates/macros/form-macro.html.j2
  src/views/templates/stocks/purchase.html.j2
  src/views/templates/stocks/sell.html.j2
Labels: front end

#22 Login and JWT Authentication
  data/create.sql
  src/api/ApiService.py
  src/api/__init__.py
  src/api/__pycache__/ResourcesService.cpython-37.pyc
  src/api/__pycache__/__init__.cpython-37.pyc
  src/api/requirements.txt
  src/controllers/UserController.py
  src/controllers/__init__.py
  src/main.py
  src/models/RevokedToken.py
  src/models/User.py
  src/models/__init__.py
Labels: back end

#24 Watchlist and JWT Blacklist
  data/create.sql
  src/Resources/MarketProvider.py
  src/Resources/__init__.py
  src/api/StockService.py
  src/api/UserService.py
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/main.py
  src/models/assets/Stock.py
Labels: back end, database, enhancement

#25 Minor deployment update
  deploy.sh
  src/Dockerfile
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/requirements.txt
Labels: bug, set up
