Repository jrg4017/stock-simulator, pull requests merged in 2019-12, with the labels that each got.

#30 Balance Management
  data/create.sql
  src/controllers/UserController.py
Labels: back end, blocked, database

#31 SQL deployment update
  data/create.sql
  deploy.sh
Labels: blocked, database

#35 Tradier API and Stock creation fix
  src/Resources/MarketProvider.py
  src/api/StockService.py
  src/api/UserService.py
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/main.py
Labels: back end, bug

#36 Reverted directory changes to enable existing PRs
  src/Api/StockService.py
  src/Api/UserService.py
  src/Api/__init__.py
  src/Controllers/StockController.py
  src/Controllers/UserController.py
  src/Controllers/__init__.py
  src/Models/Assets/Asset.py
  src/Models/Assets/Stock.py
  src/Models/Collections/AssetMap.py
  src/Models/Collections/OwnedAssets.py
  src/Models/Collections/SoldAssets.py
  src/Models/Collections/Watchlist.py
  src/Models/RevokedToken.py
  src/Models/User.py
  src/Models/__init__.py
Labels: bug

#38 add submenu for linking
  src/views/static/styles/header.css
  src/views/static/styles/login.css
  src/views/templates/header-footer/header.html.j2
Labels: front end

#39 Balance history report
  data/create.sql
  src/api/UserService.py
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/models/User.py
Labels: back end, database

#40 Quick fixes
  src/Resources/MarketProvider.py
  src/api/StockService.py
  src/controllers/UserController.py
  src/main.py
  src/models/assets/Stock.py
  src/requirements.txt
Labels: bug

#42 Final (?) deployment fix
  data/create.sql
  docker-compose.yml
  src/Dockerfile
  src/main.py
Labels: database, server

#43 User fixes
  src/api/UserService.py
  src/controllers/UserController.py
Labels: back end

#44 Stock api fixes
  src/api/StockService.py
  src/controllers/StockController.py
Labels: back end

#46 Mysql query fixes and other stuff
  src/Resources/MarketProvider.py
  src/api/StockService.py
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/main.py
  src/views/static/styles/input.css
  src/views/static/styles/main.css
  src/views/static/styles/sell.css
  src/views/templates/login/login.html.j2
  src/views/templates/login/register.html.j2
  src/views/templates/market/market.html.j2
  src/views/templates/stocks/sell.html.j2
Labels: database, front end

#47 frontend hookup
  data/create.sql
  src/Dockerfile
  src/Resources/MarketProvider.py
  src/api/StockService.py
  src/api/UserService.py
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/main.py
  src/views/static/styles/container-macro.css
  src/views/static/styles/form.css
  src/views/static/styles/header.css
  src/views/static/styles/login.css
  src/views/static/styles/main.css
  src/views/static/styles/table.css
  src/views/static/styles/watchlist.css
  src/views/templates/header-footer/header.html.j2
  src/views/templates/index.html.j2
  src/views/templates/login/login.html.j2
  src/views/templates/login/register.html.j2
  src/views/templates/stocks/owned-assets-list.html.j2
  src/views/templates/stocks/sell.html.j2
  src/views/templates/watchlist/manage.html.j2
  src/views/templates/watchlist/watchlist-cards.html.j2
  src/views/templates/watchlist/watchlist-table.html.j2
Labels: back end, enhancement, front end

#48 Julie/frontend hookup
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/main.py
  src/views/static/styles/input.css
  src/views/static/styles/main.css
  src/views/templates/stocks/sell.html.j2
  src/views/templates/watchlist/manage.html.j2
  src/views/templates/watchlist/watchlist-cards.html.j2
Labels: back end, bug, enhancement, front end

#49 Julie/fix queries
  src/.gitignore
  src/Dockerfile
  src/Resources/MarketProvider.py
  src/api/UserService.py
  src/config/.env.example
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/main.py
  src/models/User.py
  src/requirements.txt
Labels: back end, database

#50 Julie/fix queries
  src/api/UserService.py
  src/controllers/UserController.py
  src/main.py
  src/views/templates/login/register.html.j2
Labels: back end, bug

#53 dot env support
  src/.env.example
  src/Dockerfile
  src/Resources/MarketProvider.py
  src/_config.py
  src/api/StockService.py
  src/api/UserService.py
  src/controllers/StockController.py
  src/controllers/UserController.py
  src/main.py
  src/models/User.py
  src/models/assets/Stock.py
  src/settings.py
  src/views/templates/stocks/sell.html.j2
Labels: back end, bug, enhancement, front end
